### ISSUE TITLE
Resume training process

### ISSUE THREAD

**Issue by alokpadhi** [arthurflor23/handwritten-text-recognition#12]
As training for 1000 epochs in colab is taking time, I want to stop the training process at each 100 epoch and resume the training process further next time. Is there any way to do this? If you can share the pre-trained model, it will be a great help actually, because when I train on colab it's taking a lot of time, that's why I am asking for the pre-trained model. Thank you.

**Comment by arthurflor23** [comment]
Hi! I don't have anymore the pre-trained models, but is easy to get them.
The "1000 epochs" is only to training doesn't stop early.. the code use checkpoint callback, so, the weights file is save in each better epoch.. you need only run the code again and the project will load the weights automatic (if the file exists).

If you're running with the default datasets, I think the puigcerver arch with the rimes datasets (the slower combination) you will get some 7 hours training (I don't remember exactly).. Anyway, just running again and you'll already load the summary of training.

**Comment by alokpadhi** [comment]
So for how many epochs you trained to get a decent result?

**Comment by arthurflor23** [comment]
I think 100 - 150.
Bentham + rimes + LR 0.001 + early stopping (20).

LR = 0.001 isn't the best (isn't the original value in paper), but is faster with the results

And I used the Tesla P100 by google colab (you can check this with !nvidia-smi command).. sometimes we got a gpu slower in the session
