### ISSUE TITLE
Convert to Tensorflow Lite

### ISSUE THREAD

**Issue by paolopiano1997** [arthurflor23/handwritten-text-recognition#13]
Hi, I was trying to convert this model to tflite model but it seems I can't finalize this operation. I saw that layers objects are been redefined and when I try to summary the model, python gives me "ValueError: Unknown layer: FullGatedConv2D" (and same for others layers). I tried to use CustomObjects parameter, but I don't know hot to pass init parameter(in fact, it gives me error for not passing parameters). How can I convert this to tflite? Actually, CAN I do this operation? Thanks for attention.

**Comment by arthurflor23** [comment]
Hi!
I really don't know how work in tf lite.. However, did you implement the custom layers from layers.py? Maybe you can try to define them inside the model class..

**Comment by paolopiano1997** [comment]
Wait a moment...what do you mean when you say "implement the custom layers"? I mean, they are just implemented, aren't? For example, FullGatedConv2D is an implementation for Conv2D...I don't understand sorry :(
Thanks for attention and for the reply

**Comment by arthurflor23** [comment]
GatedConv2D / FullGatedConv2D / OctConv2D are custom layers implemented in layers.py file (inside ``network`` directory in the project). These layers use Conv2D, indeed, but have a different process of the filters / activations.
TF doesn't have these layers by default, so maybe is missing import this file or something like that

**Comment by paolopiano1997** [comment]
yes, in fact when it says "ValueError: Unknown layer: FullGatedConv2D" it's something like that. I tried to use customObjects parameter that enable to work with custom objects, but it doesn't work. I tried to save directly the entire model (modifying the main) and then load/convert to tflite, but other errors are raised. You don't know if there is a mode to save the hdf5 model with your custom layers/model?
Thanks.

**Comment by arthurflor23** [comment]
You can try change the ``save_weights_only`` pamereter in ModelCheckpoint callback to ``False``. If doesn't work, maybe you can save / load the model as json (it takes more work, but it works in this project [here](https://git.litislab.fr/TextRecognition/CTCModel/tree/master))

**Comment by paolopiano1997** [comment]
I tried. The problem is that the model is saved correctly, but when I have to load it and use it in another environment (like tflite) all the custom objects are not seen. If I use customObjects parameter, I noticed that the object is seen, but it cannot instantiate it because it don't know which arguments pass. For example, I tried with custom_objects={FullGatedConv2D: FullGatedConv2D} then the last error disappeares, but another one appears: "TypeError: __init__() missing 1 required positional argument: 'filters'" In fact the constructor of FullGatedConv2D wants arguments, but the target enviroment doesn't know. How I can do this? How can I export these objects and make them work correctly in tflite?

**Comment by arthurflor23** [comment]
You can try to manually set the filter values, looking at the size of the input image. These values you can get by the summary function and then setup in TF lite

**Comment by paolopiano1997** [comment]
For now, using puigcerver architecture I can converto to tflite (with some tricks). The question about using custom layers is not resolved. Maybe I can try to manually configure the filter, like you said, but from where?

**Comment by arthurflor23** [comment]
On second thought, it would be better for you to incorporate the FullGatedConv2D function into the architecture (the Conv2D, activations and multiply functions) instead of using a separate class, you know.. this way it should work just like puigcever, since they are recognized functions by TF.

**Comment by paolopiano1997** [comment]
Oh, what do you mean "to incorporate ..."? Thanks a lot.

**Comment by arthurflor23** [comment]
Instead of FullGatedConv2D calls, you can implement the Conv2D + activations + multiply process in the model class.. "FullGatedConv2D" is just an function abstraction of this steps

**Comment by paolopiano1997** [comment]
Hey, thank you for the support. I have another problem: how can I use model's output? I saw it's a float multi-dimensional array [1,128,98] but how can I elaborate this to obtain a response? Thank you!

**Comment by arthurflor23** [comment]
Just decode with the charset that you used. 
128 is the sentence length, 98 is the charset length with the probabilities.

**Comment by paolopiano1997** [comment]
Sorry, with "charset length with the probabilities" what do you mean? Are there 98 chars?

**Comment by paolopiano1997** [comment]
And "decode"? Sorry for questioning stupid things

**Comment by arthurflor23** [comment]
[1,128,98] is a matrix of probabilities with 128 positions (max sentence length) and 98 possibilities per position (characteres), you just need to take the character more probable (on each character) and then turn the number into a letter (string) with the character dictionary used to encode.

**Comment by paolopiano1997** [comment]
Why are you saying 98 possibilities? I thought they were 95, in fact in charset_base the printing is "string.printable[:95]" and the output is '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~ '  The question is: where are the last 3 possibilities?

**Comment by arthurflor23** [comment]
``generator.py``, Tokenizer class.
You have 2 more special chars, which is the ``padding`` and ``unknown`` chars. The third is the CTC special char for decode process in tetnsorflow ctc function
