### ISSUE TITLE
Predict on a single Image

### ISSUE THREAD

**Issue by alokpadhi** [arthurflor23/handwritten-text-recognition#14]
In the notebook Predict part the predictions are quite good, but when I try to run prediction on single images, with `python main.py --source=raw/Bentham --image=IMAGE_URL` it is giving me very random characters.

For example, for the below Image
[Input Image](https://drive.google.com/file/d/1jbpCzzPepo4xHN0-0MdDBwC655nDJyki/view?usp=sharing)

In notebook `Prediction` part the output is as below:
```
in paving the way to the consideration of
in pawing he way to the conkideratin or
```

But when I did for a single Image (same image used in the Prediction notebook part) it is showing output as below:
```
Prob.  - Predict
0.0000 - 0 \ 0 \ < \ 0 \ < \ < 0 < 0 \ < 0 < 0 \ < \ < 0 < \ < \ < \ 0 \ 0 \ 0T \ < \ 0 \ 0 < 0 < T
0.0000 - 0 \ 0 \ < \ 0 \ < \ < 0 < 0 \ < 0 < 0 \ < \ < 0 < \ < \ < \ 0 \ 0 \ 0T \ < \ 0 \ 0 < 0 < 0
0.0000 - 0 \ 0 \ < \ 0 \ < \ < 0 < 0 \ < 0 < 0 \ < \ < 0 < \ < \ < \ 0 \ 0 \ 0T \ < \ 0 \ 0 < 0 < )
0.0000 - 0 \ 0 \ < \ 0 \ < \ < 0 < 0 \ < 0 < 0 \ < \ < 0 < \ < \ < \ 0 \ 0 \ 0T \ < \ 0 \ 0 < 0 < 3
0.0000 - 0 \ 0 \ < \ 0 \ < \ < 0 < 0 \ < 0 < 0 \ < \ < 0 < \ < \ < \ 0 \ 0 \ 0T \ < \ 0 \ 0 < 0 < u
0.0000 - 0 \ 0 \ < \ 0 \ < \ < 0 < 0 \ < 0 < 0 \ < \ < 0 < \ < \ < \ 0 \ 0 \ 0T \ < \ 0 \ 0 < 0
0.0000 - 0 \ 0 \ < \ 0 \ < \ < 0 < 0 \ < 0 < 0 \ < \ < 0 < \ < \ < \ 0 \ 0 \ 0T \ < \ 0 \ 0 < 0 < W
0.0000 - 0 \ 0 \ < \ 0 \ < \ < 0 < 0 \ < 0 < 0 \ < \ < 0 < \ < \ < \ 0 \ 0 \ 0T \ < \ 0 \ 0 < 0 < U
0.0000 - 0 \ 0 \ < \ 0 \ < \ < 0 < 0 \ < 0 < 0 \ < \ < 0 < \ < \ < \ 0 \ 0 \ 0T \ < \ 0 \ 0 < 0 < #
0.0000 - 0 \ 0 \ < \ 0 \ < \ < 0 < 0 \ < 0 < 0 \ < \ < 0 < \ < \ < \ 0 \ 0 \ 0T \ < \ 0 \ 0 < 0 < T )
```

How can I fix this?

**Comment by arthurflor23** [comment]
Hello,
The ``--source`` parameter must be only 'bentham' to the code get the ``/data/bentham.hdf5`` and load the trained model from ``output/bentham/`` too.

**Comment by alokpadhi** [comment]
Thanks, I tested it. It's working.
