### ISSUE TITLE
Memory leak in finalizing GeneratorDataset iterator

### ISSUE THREAD

**Issue by poly-kay** [arthurflor23/handwritten-text-recognition#17]
output warning message Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was canceled when I am using tf.keras.model.fit(..., worker = 1) start to train to next epoch. 

When tf.keras.model.fit(..., worker = 1) the error message print out and the memory does not get freed in the next epoch. After training a few models. All the memory is occupied and the process gets killed. 

There is an open issue on - https://github.com/tensorflow/tensorflow/issues/36919. 

I've so far tried reinstalling my GPU Driver to 431.86 (Studio driver), tweaking the batch_size to be larger than 16, and other hyper-parameters and so far I still see this error occur during training. Although, when you increase the batch_size I am able to continue longer until a sudden stop. This happened without any error showing up in colab where it just stopped training on 168th epoch whereas running this in my local machine displays the error messages and stops after some iterations.

**Comment by arthurflor23** [comment]
I also had some problems like that, resulting from TF.. Unfortunately it is just wait for someone to correct them, or test other versions. I used the Beta1 version, if I'm not mistaken.. it's been a long time. Right now have TF 2.2.0-rc1 to test
