### ISSUE TITLE
how to execute the predict algorithm

### ISSUE THREAD

**Issue by vishalg01** [arthurflor23/handwritten-text-recognition#2]
ImportError: cannot import name 'preproc'
 getting this error when trying it to execute in google colab.

from data import preproc as pp
from google.colab.patches import cv2_imshow

start_time = time.time()

# predict() function will return the predicts with the probabilities
predicts, _ = model.predict(x=dtgen.next_test_batch(),
                            steps=dtgen.steps['test'],
                            ctc_decode=True,
                            verbose=1)

# decode to string
predicts = [dtgen.tokenizer.decode(x[0]) for x in predicts]

total_time = time.time() - start_time

# mount predict corpus file
with open(os.path.join(output_path, "predict.txt"), "w") as lg:
    for pd, gt in zip(predicts, dtgen.dataset['test']['gt']):
        lg.write(f"TE_L {gt}\nTE_P {pd}\n")
   
for i, item in enumerate(dtgen.dataset['test']['dt'][:10]):
    print("=" * 1024, "\n")
    cv2_imshow(pp.adjust_to_see(item))
    print(dtgen.dataset['test']['gt'][i])
    print(predicts[i], "\n")

**Comment by arthurflor23** [comment]
preproc is a function in src/data/preproc.py:
```from data import preproc as pp```

You need upload src folder to gdrive (step 1) and mount partition (step 2)

**Comment by ronin2095** [comment]
Hi ,
Thanks for the reply . I have already done it but don’t know why it didn't
work. the error is still showing up when tried to execute the predict
algorithm in colab . actually i'm new to the python and these ML libraries
so finding it little bit confusing to get the final output , where to
execute and all
Thanks for the reply.

**Comment by ronin2095** [comment]
yes i have done the same but don't know why the error is still showing up.
Thanks.

**Comment by vishalg01** [comment]
sometimes this error shows up instead of "preproc"

NameError                                 Traceback (most recent call last)

<ipython-input-13-0467c70e3d49> <https://localhost:8080/#> in <module>()
----> 1 start_time = time.time()      2       3 h =
model.fit(x=dtgen.next_train_batch(),      4
epochs=epochs,      5
steps_per_epoch=dtgen.steps['train'],


NameError: name 'time' is not defined

**Comment by arthurflor23** [comment]
Maybe this happens because gdrive disconnect with colab (even connect later), so you will lose the import commands ```import time``` for example..  or just was an upload file error.. in this case, you open the file (gdrive) and check if the code is there.. sometimes I get a file in blank here, so I delete them and upload again (I don't know why)

**Comment by vishalg01** [comment]
Oh , I’ll check that . So if that predict algorithm is executed then we
will get the output right ? When we perform “python main.py
—source=Washington —cv2”.Thank you very much

**Comment by arthurflor23** [comment]
Yeah, if predict step is executed, predictions will be saved into txt file and with --cv2 parameter, you'll see the images in hdf5, ground truth and predicts (if exist)

**Comment by vishalg01** [comment]
Hi,
The following error is coming up when i try to run the predict algorithm.
Can you please guide me how to resolve this?


Model Predict 10/10 [==============================] - 14s 1s/step CTC
Decode

---------------------------------------------------------------------------

OperatorNotAllowedInGraphError            Traceback (most recent call last)

<ipython-input-14-e89836b0202a> <https://localhost:8080/#> in
<module>()      8
steps=dtgen.steps['test'],      9
ctc_decode=True,
---> 10                             verbose=1)     11      12 # decode to string


------------------------------
4 frames
------------------------------

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py
<https://localhost:8080/#> in _disallow_in_graph_mode(self, task)
521     raise errors.OperatorNotAllowedInGraphError(    522
"{} is not allowed in Graph execution. Use Eager execution or
decorate"
--> 523         " this function with @tf.function.".format(task))
524     525   def _disallow_bool_casting(self):


OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not
allowed in Graph execution. Use Eager execution or decorate this
function with @tf.function.

**Comment by arthurflor23** [comment]
Hi!
Maybe it's the version of tensorflow, what version do you use?

**Comment by vishalg01** [comment]
Thanks ,
Tensorflow version was 1.15  in the colab !
and tensorflow 2.0.0 in the local machine. now updated the colab version to
2.0.

**Comment by arthurflor23** [comment]
Try 2.1-rc2, if you can
2.0 version has some bugs that I reported

**Comment by vishalg01** [comment]
okay upgraded to 2.1-rc2 !!  can we give our own sample input jpeg file as
input in place of the dataset
and after upgrading to tensorflow 2.1-rc2 , when i ran the "HTR model
class" the following error is occurring

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-5-1b228a635105> <https://localhost:8080/#> in
<module>()     10      11 # get default callbacks and load checkpoint
weights file (HDF5) if exists
---> 12 model.load_checkpoint(target=target_path)     13      14
callbacks = model.get_callbacks(logdir=output_path,
checkpoint=target_path, verbose=1)


------------------------------
7 frames
------------------------------

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/hdf5_format.py
<https://localhost:8080/#> in _convert_rnn_weights(layer, weights)
560       types = (source, target)    561       if
'GRU(reset_after=False)' in types:
--> 562         raise ValueError('%s is not compatible with %s' %
types)    563       if source == 'CuDNNGRU':    564         weights =
convert_gru_weights(weights, from_cudnn=True)


ValueError: GRU(reset_after=False) is not compatible with GRU(reset_after=True)
