### ISSUE TITLE
Error While Using data.generator 

### ISSUE THREAD

**Issue by JasserAlharbi** [arthurflor23/handwritten-text-recognition#22]
Hello Arthur,
This is a great project. I ran it on the jupyter notebook on Google Colab, 
While I trying it out I face an error that the no module named 'data'. 
Could you help me with this ?
Thanks

`
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-18-1b46b1350bbc> in <module>()
----> 1 from data.generator import DataGenerator
      2 
      3 dtgen = DataGenerator(source=source_path,
      4                       batch_size=batch_size,
      5                       charset=charset_base,

ModuleNotFoundError: No module named 'data'
`

**Comment by arthurflor23** [comment]
Hi!
Maybe the file (data/generator.py) is blank on gdrive (this happened to me ~ upload error) or maybe the file location is different when mounting the gdrive partition
