### ISSUE TITLE
InvalidArgumentError: 2 root error(s) found.

### ISSUE THREAD

**Issue by abdoelsayed2016** [arthurflor23/handwritten-text-recognition#23]
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-13-4321e24f045a> in <module>
      9               callbacks=callbacks,
     10               shuffle=True,
---> 11               verbose=1)
     12 
     13 total_time = datetime.datetime.now() - start_time

~\Desktop\handwritten-text-recognition\src\network\model.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    171                              validation_steps=validation_steps, validation_freq=validation_freq,
    172                              max_queue_size=max_queue_size, workers=workers,
--> 173                              use_multiprocessing=use_multiprocessing, **kwargs)
    174         return out
    175 

~\Anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    817         max_queue_size=max_queue_size,
    818         workers=workers,
--> 819         use_multiprocessing=use_multiprocessing)
    820 
    821   def evaluate(self,

~\Anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    340                 mode=ModeKeys.TRAIN,
    341                 training_context=training_context,
--> 342                 total_epochs=epochs)
    343             cbks.make_logs(model, epoch_logs, training_result, ModeKeys.TRAIN)
    344 

~\Anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
    126         step=step, mode=mode, size=current_batch_size) as batch_logs:
    127       try:
--> 128         batch_outs = execution_function(iterator)
    129       except (StopIteration, errors.OutOfRangeError):
    130         # TODO(kaftan): File bug about tf function and errors.OutOfRangeError?

~\Anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py in execution_function(input_fn)
     96     # `numpy` translates Tensors to values in Eager mode.
     97     return nest.map_structure(_non_none_constant_value,
---> 98                               distributed_function(input_fn))
     99 
    100   return execution_function

~\Anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\eager\def_function.py in __call__(self, *args, **kwds)
    566         xla_context.Exit()
    567     else:
--> 568       result = self._call(*args, **kwds)
    569 
    570     if tracing_count == self._get_tracing_count():

~\Anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\eager\def_function.py in _call(self, *args, **kwds)
    597       # In this case we have created variables on the first call, so we run the
    598       # defunned version which is guaranteed to never create variables.
--> 599       return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
    600     elif self._stateful_fn is not None:
    601       # Release the lock early so that multiple threads can perform the call

~\Anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\eager\function.py in __call__(self, *args, **kwargs)
   2361     with self._lock:
   2362       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 2363     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2364 
   2365   @property

~\Anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\eager\function.py in _filtered_call(self, args, kwargs)
   1609          if isinstance(t, (ops.Tensor,
   1610                            resource_variable_ops.BaseResourceVariable))),
-> 1611         self.captured_inputs)
   1612 
   1613   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

~\Anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1690       # No tape is watching; skip to running the function.
   1691       return self._build_call_outputs(self._inference_function.call(
-> 1692           ctx, args, cancellation_manager=cancellation_manager))
   1693     forward_backward = self._select_forward_and_backward_functions(
   1694         args,

~\Anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\eager\function.py in call(self, ctx, args, cancellation_manager)
    543               inputs=args,
    544               attrs=("executor_type", executor_type, "config_proto", config),
--> 545               ctx=ctx)
    546         else:
    547           outputs = execute.execute_with_cancellation(

~\Anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     65     else:
     66       message = e.message
---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
     68   except TypeError as e:
     69     keras_symbolic_tensors = [

~\Anaconda3\envs\handwritten\lib\site-packages\six.py in raise_from(value, from_value)

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Labels length is zero in batch 0
	 [[node loss/dense_1_loss/CTCLoss (defined at C:\Users\a.abdallah\Desktop\handwritten-text-recognition\src\network\model.py:259) ]]
	 [[loss/dense_1_loss/CTCLoss/_126]]
  (1) Invalid argument:  Labels length is zero in batch 0
	 [[node loss/dense_1_loss/CTCLoss (defined at C:\Users\a.abdallah\Desktop\handwritten-text-recognition\src\network\model.py:259) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_17974]

Function call stack:
distributed_function -> distributed_function

**Comment by arthurflor23** [comment]
The "Labels length is zero in batch"
```
InvalidArgumentError: 2 root error(s) found.
(0) Invalid argument: Labels length is zero in batch 0
[[node loss/dense_1_loss/CTCLoss (defined at C:\Users\a.abdallah\Desktop\handwritten-text-recognition\src\network\model.py:259) ]]
[[loss/dense_1_loss/CTCLoss/_126]]
(1) Invalid argument: Labels length is zero in batch 0
```

I think the hdf5 file was read wrong or the data is preprocessed incorrectly

**Comment by abdoelsayed2016** [comment]
I found the problem it is because of the encoding the text 
text = unicodedata.normalize("NFKD", text).encode("ASCII", "ignore").decode("ASCII")
because I am working with Russian not English

**Comment by arthurflor23** [comment]
Oh, I see,
I think you need change the charset too (current is chars from ASCII)
