### ISSUE TITLE
Error  while running Environment in colab

### ISSUE THREAD

**Issue by sanjanakancharla** [arthurflor23/handwritten-text-recognition#26]
Hello Arthur,

Please help me to resolve this error while setting the environment in google colab,

import os
import datetime
import string

# define parameters
source = "bentham"
arch = "flor"
epochs = 1000
batch_size = 16

# define paths
source_path = os.path.join("..", "data", f"{source}.hdf5")
output_path = os.path.join("..", "output", source, arch)
target_path = os.path.join(output_path, "checkpoint_weights.hdf5")
os.makedirs(output_path, exist_ok=True)

# define input size, number max of chars per line and list of valid chars
input_size = (1024, 128, 1)
max_text_length = 128
charset_base = string.printable[:95]

print("source:", source_path)
print("output", output_path)
print("target", target_path)
print("charset:", charset_base)

**OSError                                   Traceback (most recent call last)
<ipython-input-11-9fff1c467c4e> in <module>()
     13 output_path = os.path.join("..", "output", source, arch)
     14 target_path = os.path.join(output_path, "checkpoint_weights.hdf5")
---> 15 os.makedirs(output_path, exist_ok=True)
     16 
     17 # define input size, number max of chars per line and list of valid chars

2 frames
/usr/lib/python3.6/os.py in makedirs(name, mode, exist_ok)
    218             return
    219     try:
--> 220         mkdir(name, mode)
    221     except OSError:
    222         # Cannot rely on checking for EEXIST, since the operating system**

OSError: [Errno 107] Transport endpoint is not connected: '../output'**
![image](https://user-images.githubusercontent.com/38933770/78714371-669ec780-7939-11ea-85ef-46c58209be04.png)

**Comment by arthurflor23** [comment]
Hi,
With this:
`OSError: [Errno 107] Transport endpoint is not connected: '../output'**`
I think that is disconnect colab problem with gdrive.

Try to unmount and mount the drive again, or restart the session (as suggested [here](https://stackoverflow.com/questions/49588113/google-colab-script-throws-transport-endpoint-is-not-connected))

**Comment by sanjanakancharla** [comment]
Thank you arthur!!!! This is an awesome project!!
