### ISSUE TITLE
 Unable to open file (truncated file: eof = 10485760, sblock->base_addr = 0, stored_eof = 372841106)

### ISSUE THREAD

**Issue by Rach523** [arthurflor23/handwritten-text-recognition#27]
hey,
Error in DataGenerator() class

OSError                                   Traceback (most recent call last)
<ipython-input-15-1b46b1350bbc> in <module>()
      4                       batch_size=batch_size,
      5                       charset=charset_base,
----> 6                       **max_text_length=max_text_length)**
      7 
      8 print(f"Train images: {dtgen.size['train']}")

2 frames
/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    171         if swmr and swmr_support:
    172             flags |= h5f.ACC_SWMR_READ
--> 173         fid = h5f.open(name, flags, fapl=fapl)
    174     elif mode == 'r+':
    175         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

**OSError: Unable to open file (truncated file: eof = 10485760, sblock->base_addr = 0, stored_eof = 372841106)**

**Comment by arthurflor23** [comment]
hey,
the hdf5 file is corrupt (truncated file). Try to delete this old file and create it again.

**Comment by Rach523** [comment]
ok,thanks
