### ISSUE TITLE
how to use tensorflow in CPU only mode 

### ISSUE THREAD

**Issue by vishalg01** [arthurflor23/handwritten-text-recognition#6]
Hi , when trying to execute the HTR model , getting an error "ValueError: GRU(reset_after=False) is not compatible with GRU(reset_after=True)" .
I think it is due to the GPU mode and i  have only integrated graphics installed in my PC.
so is there way to change it so that it works in CPU only mode??

i have found a solution for this so that you can use GPU trained models for the inference on CPU-only instances. but don't know where to change it !!
solution:
GRU

if tf.test.is_gpu_available():
    return tf.compat.v1.keras.layers.CuDNNGRU(units,
                                              return_sequences=True,
                                              return_state=True,
                                              recurrent_initializer='glorot_uniform')
else:
    return tf.keras.layers.GRU(units, 
                               return_sequences=True,
                               return_state=True,
                               recurrent_activation='sigmoid',
                               reset_after='True',
                               recurrent_initializer='glorot_uniform')

**Comment by arthurflor23** [comment]
Hi
did you manually set `reset_after` parameter? To work with cuDNN, tensorflow brings some [requirements](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/GRU), included `reset_after=True`.

You can also have `tensorflow-gpu` and use cpu mode disabling the os.environ["CUDA_VISIBLE_DEVICES"], or just installing `tensorflow` module instead gpu version

**Comment by vishalg01** [comment]
Hi,
No i didn't set reset_after or  any other thing manually . I have installed just tensorflow instead of tensorflow-gpu. But still getting the value error GRU reset_after

**Comment by arthurflor23** [comment]
Did you try setting CUDA_VISIBLE_DEVICES environment?
Also try the new version 2.1 of the tensorflow.. this weird 'cause I use gpu version and I can use only cpu with no errors

**Comment by vishalg01** [comment]
okay thanks i''ll try to solve it.
yes installed 2.1 version and tried setting CUDA_VISIBLE_DEVICES env in the HTRmodel but didn't work.

1. %env CUDA_DEVICE_ORDER=PCI_BUS_ID
    %env CUDA_VISIBLE_DEVICES=0 and
2. os.environ["CUDA_VISIBLE_DEVICES"]="-1"

**Comment by vishalg01** [comment]
when executed 
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

the output is : 
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 12363724970508031367
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 71252367667276204
physical_device_desc: "device: XLA_CPU device"
]

so it is in cpu mode only but 

when executing HTR model 
from network.model import HTRModel ::::

# create and compile HTRModel

model = HTRModel(architecture=arch, input_size=input_size, vocab_size=dtgen.tokenizer.vocab_size)
model.compile(learning_rate=0.001)


model.summary(output_path, "summary.txt")


model.load_checkpoint(target=target_path)

callbacks = model.get_callbacks(logdir=output_path, checkpoint=target_path, verbose=1)

THE OUTPUT I'm getting is :::

ValueError                                Traceback (most recent call last)
<ipython-input-5-1b228a635105> in <module>()
     10 
     11 # get default callbacks and load checkpoint weights file (HDF5) if exists
---> 12 model.load_checkpoint(target=target_path)
     13 
     14 callbacks = model.get_callbacks(logdir=output_path, checkpoint=target_path, verbose=1)

7 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/hdf5_format.py in _convert_rnn_weights(layer, weights)
    560       types = (source, target)
    561       if 'GRU(reset_after=False)' in types:
--> 562         raise ValueError('%s is not compatible with %s' % types)
    563       if source == 'CuDNNGRU':
    564         weights = convert_gru_weights(weights, from_cudnn=True)

ValueError: GRU(reset_after=False) is not compatible with GRU(reset_after=True)

**Comment by arthurflor23** [comment]
I think it is still using tf.compat.v1.keras.layers.CuDNNGRU.. I saw this function version doesn't have reset_after, making default value False. I found this [issue](https://github.com/tensorflow/tensorflow/issues/36014) in tensorflow repository about this error.

**Comment by vishalg01** [comment]
Hey ! thanks for helping me out . The model is succesfully working now . As you said maybe the problem is also with the google colab. I freshly downloaded  the code again from the github and tried this time in a system with GPU and it worked . Then tried in my system again with cpu only mode and it successfully worked this time . thank you

**Comment by vishalg01** [comment]
And one more thing how to give the model our own input image like a single jpeg file ?

**Comment by arthurflor23** [comment]
Great!

> And one more thing how to give the model our own input image like a single jpeg file ?

You need add `--image=<IMAGE_URL>` parameter instead `--test`

**Comment by vishalg01** [comment]
so can we just place an jpg file in data folder and perform "python main.py --source=<image_url> --image " will do the trick ? 
this is the errorcoming when  tried !python main.py --source=img --image=img
    h, w = np.asarray(img).shape
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by arthurflor23** [comment]
Hey, almost

python main.py --source=<DATASET> --image=<IMAGE_URL>

The source is the dataset model that you want to load (bentham, iam, rimes...)

The image is the path of image (/home/user/image.png)

**Comment by vishalg01** [comment]
Hey it worked in the studio code but prediction was wrong . Is it because i have done all the setup in google colab but not locally so  the prediction isn't working ?

when i tried in colab it is giving
  File "main.py", line 99, in <module>
    img = pp.preprocess(args.image, input_size=input_size)
  File "/content/drive/My Drive/gpu/handwritten-text-recognition-master/handwritten-text-recognition-master/src/data/preproc.py", line 119, in preprocess
    h, w = np.asarray(img).shape
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by arthurflor23** [comment]
> Is it because i have done all the setup in google colab but not locally so the prediction isn't working ?

I think not, the image is in the pattern with the source model, right?

> when i tried in colab it is giving
> File "main.py", line 99, in
> img = pp.preprocess(args.image, input_size=input_size)
> File "/content/drive/My Drive/gpu/handwritten-text-recognition-master/handwritten-text-recognition-master/src/data/preproc.py", line 119, in preprocess
> h, w = np.asarray(img).shape
> ValueError: not enough values to unpack (expected 2, got 0)

In Colab, you're probably not reading the image in the correct directory, so it returns shape == 0

**Comment by vishalg01** [comment]
Hey  , yeah its becoming a real pain with this colab eventhough the path given is right it will not access the file. So uploaded the file directly in the colab in the  runtime now it recognised the file from the given path.
Now coming to the wrong prediction , so i have given a single sentence written on a paper as input while using washington dataset. Here  have given the image of non cursive writing and i think the washington dataset contains cursive writing data . so will that be a problem ?
sorry for bothering you but thanks for helping me out

**Comment by arthurflor23** [comment]
I think so, the images must have the same pattern (train/validation/test).. you can try IAM dataset to train, but I think will get the same problem with another external image. Ideal would be to train with your image pattern, or attach the pattern within a dataset (I think it can work too).

**Comment by vishalg01** [comment]
oh okay i'll try it that way .I had problem with downloading the IAM dataset with link "http://www.fki.inf.unibe.ch/databases/iam-handwriting-database/download-the-iam-handwriting-database" , it says connection to this site is not private 
is it the only source ? if not can you share any link for downloading the dataset !

**Comment by arthurflor23** [comment]
Yes, you must register and login after on the site. 
And again, I don't know if that will help you with the external predictions.
