### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by piotr-rarus** [arthurflor23/handwritten-text-recognition#8]
Hey Arthur Flôr, thanks for the repo!
I was wondering, if you could share pretrained models (.h5 files).
I've seen them in examples, but there're no files in `raw` directory.

**Comment by arthurflor23** [comment]
Hey! Thanks for interest!

Actually I moved to another project and I haven't the models here anymore. Anyway, `raw` folder is where you put the dataset files (download from source site) and run `--transform` parameter to make a .hdf5 file (`data` folder).. It'll contains all images preprocessed and the GT encoded. Then, running `--train` you will get the model training in `output/<dataset>/<arch>`

I know, many steps, but it's easy to reproduce. If you have any questions, don't hesitate to ask.
